/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.models.Expense;
import app.models.Vaccination;
import app.screens.MonetaryScreen;
import app.utils.AppUtils;
import connector.DbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Eco
 */
public class AddExpense extends javax.swing.JFrame {

    /**
     * Creates new form AddExpense
     */
    private static Connection conn;
    private Expense vaccination;
       
    public AddExpense() {
        initComponents();
        
        conn = DbConnection.getConnection();
        
        vaccination = new Expense();
        AutoCompleteDecorator.decorate(goatTags);
        populateGoatTags();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        goatTags = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        expenseDate = new com.toedter.calendar.JDateChooser();
        expenseCost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancelDeworm = new javax.swing.JButton();
        addVaccinationBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        expenseItem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(goatTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 42, 153, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Goat Tag");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 41, -1, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Expense Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));
        jPanel1.add(expenseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 220, 30));

        expenseCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expenseCostKeyPressed(evt);
            }
        });
        jPanel1.add(expenseCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Cost");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 30));

        cancelDeworm.setBackground(new java.awt.Color(255, 102, 102));
        cancelDeworm.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cancelDeworm.setForeground(new java.awt.Color(255, 255, 255));
        cancelDeworm.setText("CANCEL");
        cancelDeworm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDewormActionPerformed(evt);
            }
        });
        jPanel1.add(cancelDeworm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 40));

        addVaccinationBtn.setBackground(new java.awt.Color(61, 149, 119));
        addVaccinationBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addVaccinationBtn.setForeground(new java.awt.Color(255, 255, 255));
        addVaccinationBtn.setText("ADD");
        addVaccinationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccinationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addVaccinationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 160, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Item");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));
        jPanel1.add(expenseItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 390));

        jPanel2.setBackground(new java.awt.Color(61, 149, 119));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Expense Record");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelDewormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDewormActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelDewormActionPerformed

    private void populateGoatTags() {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement("SELECT * FROM goat");
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                goatTags.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AppUtils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
      public boolean validateText() {
        
        if (expenseItem.getText().equals("") 
                || expenseDate.getDate() == null || expenseItem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "All fields must be filled!");
            return false;
        } else if (expenseDate.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "Please choose date which is not in the future.");
            return false;
        } else {       
            return true;
        }
    }
      
    private void addVaccinationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccinationBtnActionPerformed
        vaccination.setCost(Integer.parseInt(expenseCost.getText()));
        vaccination.setItem(expenseItem.getText());
        vaccination.setGoatTag(String.valueOf(goatTags.getSelectedItem()));

        if (validateText()) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String eDate = dateFormat.format(expenseDate.getDate());

            vaccination.setExpenseDate(eDate);

            AppUtils.addExpense(vaccination, this);
            MonetaryScreen.expenseTable.setModel(new DefaultTableModel(null, new Object[]{"ID", "Exepense Date", "Item", "Cost", "Goat Tag"}));
            AppUtils.fillExpenseTable(MonetaryScreen.expenseTable, "");
        }
    }//GEN-LAST:event_addVaccinationBtnActionPerformed

    private void expenseCostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expenseCostKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)) {
            expenseCost.setEditable(false);
        } else {
            expenseCost.setEditable(true);
        }
    }//GEN-LAST:event_expenseCostKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccinationBtn;
    private javax.swing.JButton cancelDeworm;
    private javax.swing.JTextField expenseCost;
    private com.toedter.calendar.JDateChooser expenseDate;
    private javax.swing.JTextField expenseItem;
    private javax.swing.JComboBox<String> goatTags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
