/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.models.Goat;
import app.screens.Home;
import app.utils.AppUtils;
import java.awt.FileDialog;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eco
 */
public class AddGoat extends javax.swing.JFrame {

    /**
     * Creates new form AddGoat
     */
    Goat goat;
    public AddGoat() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rb_male);
        bg.add(rb_female);
        rb_male.setSelected(true);
        goat = new Goat();
        currentStatus.addItem("In the farm");        
        currentStatus.addItem("Not in the farm");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        goat_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        goat_source = new javax.swing.JTextField();
        goat_name = new javax.swing.JTextField();
        goat_breed = new javax.swing.JTextField();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        button_add_goat = new javax.swing.JButton();
        button_cancel_add = new javax.swing.JButton();
        goat_birth_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        buck_id = new javax.swing.JTextField();
        doe_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        frontImage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sideImage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rearImage = new javax.swing.JLabel();
        chooseFront = new javax.swing.JLabel();
        chooseSide = new javax.swing.JLabel();
        chooseRear = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        currentStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Goat ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 93, -1, -1));

        goat_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goat_idActionPerformed(evt);
            }
        });
        jPanel1.add(goat_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 87, 213, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 141, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Breed");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 194, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Sex");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 243, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Source");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 293, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Birth Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 343, -1, -1));

        goat_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goat_sourceActionPerformed(evt);
            }
        });
        jPanel1.add(goat_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 287, 213, -1));

        goat_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goat_nameActionPerformed(evt);
            }
        });
        jPanel1.add(goat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 135, 213, -1));

        goat_breed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goat_breedActionPerformed(evt);
            }
        });
        jPanel1.add(goat_breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 188, 213, -1));

        rb_male.setText("Male");
        rb_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_maleActionPerformed(evt);
            }
        });
        jPanel1.add(rb_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 242, -1, -1));

        rb_female.setText("Female");
        rb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(rb_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 242, -1, -1));

        button_add_goat.setBackground(new java.awt.Color(46, 128, 155));
        button_add_goat.setForeground(new java.awt.Color(255, 255, 255));
        button_add_goat.setText("Add");
        button_add_goat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_goatActionPerformed(evt);
            }
        });
        jPanel1.add(button_add_goat, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 539, 126, -1));

        button_cancel_add.setBackground(new java.awt.Color(255, 51, 51));
        button_cancel_add.setForeground(new java.awt.Color(255, 255, 255));
        button_cancel_add.setText("Cancel");
        button_cancel_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancel_addActionPerformed(evt);
            }
        });
        jPanel1.add(button_cancel_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 539, -1, -1));
        jPanel1.add(goat_birth_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 331, 213, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Buck ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        buck_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buck_idActionPerformed(evt);
            }
        });
        jPanel1.add(buck_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 87, 208, -1));

        doe_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doe_idActionPerformed(evt);
            }
        });
        jPanel1.add(doe_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 135, 208, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Current Status");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 20));

        jLabel14.setText("Select Images");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        frontImage.setBackground(new java.awt.Color(255, 255, 255));
        frontImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frontImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frontImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frontImage, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frontImage, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        sideImage.setBackground(new java.awt.Color(255, 255, 255));
        sideImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideImage, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, 107));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        rearImage.setBackground(new java.awt.Color(255, 255, 255));
        rearImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rearImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rearImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rearImage, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rearImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 107));

        chooseFront.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chooseFront.setText("Choose front");
        chooseFront.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseFrontMouseClicked(evt);
            }
        });
        jPanel1.add(chooseFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        chooseSide.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chooseSide.setText("Choose side");
        chooseSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseSideMouseClicked(evt);
            }
        });
        jPanel1.add(chooseSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        chooseRear.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chooseRear.setText("Choose rear");
        chooseRear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseRearMouseClicked(evt);
            }
        });
        jPanel1.add(chooseRear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        jPanel2.setBackground(new java.awt.Color(61, 149, 119));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Record");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Doe ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        currentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentStatusActionPerformed(evt);
            }
        });
        jPanel1.add(currentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 186, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goat_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goat_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goat_idActionPerformed

    private void goat_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goat_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goat_sourceActionPerformed

    private void goat_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goat_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goat_nameActionPerformed

    private void goat_breedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goat_breedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goat_breedActionPerformed

    private void rb_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_maleActionPerformed

    private void rb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_femaleActionPerformed

    private void button_cancel_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancel_addActionPerformed
       this.dispose();
    }//GEN-LAST:event_button_cancel_addActionPerformed

    public boolean validateText() {
        
        if (goat_id.getText().equals("") || goat_name.getText().equals("") || goat_breed.getText().equals("")
                || goat_birth_date.getDate() == null || goat_source.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "All fields must be filled!");
            return false;
        } else if (goat_birth_date.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "Please choose date which is not in the future.");
            return false;
        } else {       
            return true;
        }
    }
    
    private void button_add_goatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_goatActionPerformed
        String sex = "Male";
        if (rb_female.isSelected()) {
            sex = "Female";
        }
        goat.setID(goat_id.getText());
        goat.setName(goat_name.getText());
        goat.setBreed(goat_breed.getText());
        goat.setSex(sex);
        goat.setSource(goat_source.getText());
        goat.setBuck_id(buck_id.getText());        
        goat.setDoe_id(doe_id.getText());
        
        if (validateText()) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(goat_birth_date.getDate());
            goat.setBirthDate(bdate);
            
//            AppUtils.manipulateGoat(AppUtils.INSERT, goat, this, null);
            AppUtils.addNewGoat(goat, this);
            MainApp.registered_goats.setText(Integer.toString(AppUtils.countData(("goat"))));
            Home.AllGoatsTable.setModel(new DefaultTableModel(null, new Object[]{"ID", "Name", "Breed", "Sex", "Source", "BirthDate", "BuckID", "DoeID"}));
            AppUtils.fillGoatTable(Home.AllGoatsTable, "");
        }
        
    }//GEN-LAST:event_button_add_goatActionPerformed

    private void buck_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buck_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buck_idActionPerformed

    private void doe_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doe_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doe_idActionPerformed

    private void frontImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frontImageMouseClicked
      
    }//GEN-LAST:event_frontImageMouseClicked

    private void sideImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sideImageMouseClicked

    private void rearImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rearImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rearImageMouseClicked

    private void chooseFrontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseFrontMouseClicked
        FileInputStream fis = null;
        
        FileDialog fd = new FileDialog(this);
        fd.show();
        String path = fd.getDirectory()+fd.getFile();
        frontImage.setIcon(AppUtils.resizeImage(path, frontImage));
            
        try {
            File image = new File(path);
            fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            for(int readNum; (readNum=fis.read(buffer))!=-1;) {
                bos.write(buffer, 0, readNum);
            }
            goat.setImage_front(bos.toByteArray());
        } catch (Exception ex) {
            Logger.getLogger(AddGoat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_chooseFrontMouseClicked

    private void chooseSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseSideMouseClicked
        // TODO add your handling code here:
        FileInputStream fis = null;
        
        FileDialog fd = new FileDialog(this);
        fd.show();
        String path = fd.getDirectory()+fd.getFile();
        sideImage.setIcon(AppUtils.resizeImage(path, sideImage));
            
        try {
            File image = new File(path);
            fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            for(int readNum; (readNum=fis.read(buffer))!=-1;) {
                bos.write(buffer, 0, readNum);
            }
            goat.setImage_side(bos.toByteArray());
        } catch (Exception ex) {
            Logger.getLogger(AddGoat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_chooseSideMouseClicked

    private void chooseRearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseRearMouseClicked
        // TODO add your handling code here:
        FileInputStream fis = null;
        
        FileDialog fd = new FileDialog(this);
        fd.show();
        String path = fd.getDirectory()+fd.getFile();
        rearImage.setIcon(AppUtils.resizeImage(path, rearImage));
            
        try {
            File image = new File(path);
            fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            for(int readNum; (readNum=fis.read(buffer))!=-1;) {
                bos.write(buffer, 0, readNum);
            }
            goat.setImage_rear(bos.toByteArray());
        } catch (Exception ex) {
            Logger.getLogger(AddGoat.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_chooseRearMouseClicked

    private void currentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGoat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGoat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buck_id;
    private javax.swing.JButton button_add_goat;
    private javax.swing.JButton button_cancel_add;
    private javax.swing.JLabel chooseFront;
    private javax.swing.JLabel chooseRear;
    private javax.swing.JLabel chooseSide;
    private javax.swing.JComboBox<String> currentStatus;
    private javax.swing.JTextField doe_id;
    private javax.swing.JLabel frontImage;
    private com.toedter.calendar.JDateChooser goat_birth_date;
    private javax.swing.JTextField goat_breed;
    private javax.swing.JTextField goat_id;
    private javax.swing.JTextField goat_name;
    private javax.swing.JTextField goat_source;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JLabel rearImage;
    private javax.swing.JLabel sideImage;
    // End of variables declaration//GEN-END:variables
}
