/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.models.GoatOwner;
import app.models.Vaccination;
import app.screens.GoatOwnerScreen;
import app.screens.HealthScreen;
import app.utils.AppUtils;
import static app.utils.Helpers.DEFAULT_TEXT;
import connector.DbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Eco
 */
public class AddOwner extends javax.swing.JFrame {

    /**
     * Creates new form AddOwner
     */
    GoatOwner goatOwner;
   private static Connection conn;
    public AddOwner() {
        initComponents();
        
        conn = DbConnection.getConnection();
        
        goatOwner = new GoatOwner();
         AutoCompleteDecorator.decorate(goatTags);
       populateGoatTags();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        goatTags = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ownerPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancelDeworm = new javax.swing.JButton();
        addVaccinationBtn = new javax.swing.JButton();
        ownerName = new javax.swing.JTextField();
        ownerAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ownerFarm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 149, 119));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Goat Owner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(goatTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 42, 153, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Goat Tag");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 41, -1, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 30));
        jPanel1.add(ownerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 220, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 30));

        cancelDeworm.setBackground(new java.awt.Color(255, 102, 102));
        cancelDeworm.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cancelDeworm.setForeground(new java.awt.Color(255, 255, 255));
        cancelDeworm.setText("CANCEL");
        cancelDeworm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDewormActionPerformed(evt);
            }
        });
        jPanel1.add(cancelDeworm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 40));

        addVaccinationBtn.setBackground(new java.awt.Color(61, 149, 119));
        addVaccinationBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        addVaccinationBtn.setForeground(new java.awt.Color(255, 255, 255));
        addVaccinationBtn.setText("ADD");
        addVaccinationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccinationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addVaccinationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 160, 40));
        jPanel1.add(ownerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));
        jPanel1.add(ownerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 220, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Farm");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, 30));
        jPanel1.add(ownerFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 880, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelDewormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDewormActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelDewormActionPerformed

    private void populateGoatTags() {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement("SELECT * FROM goat");
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                goatTags.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AppUtils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validateText() {
        
        if (ownerPhone.getText().equals("") || ownerName.getText().equals("")
                || ownerAddress.getText().equals("") || ownerFarm.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "All fields must be filled!");
            return false;
        } else {       
            return true;
        }
    }
    
    private void addVaccinationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccinationBtnActionPerformed
        String name = ownerName.getText();
        String address = ownerAddress.getText();
        String farm = ownerFarm.getText();
        String phone = ownerPhone.getText();
        String tag = String.valueOf(goatTags.getSelectedItem());
        
        goatOwner.setName( (name.isEmpty()) ? DEFAULT_TEXT : name);
        goatOwner.setAdress((address.isEmpty()) ? DEFAULT_TEXT : address);
        goatOwner.setFarm((farm.isEmpty()) ? DEFAULT_TEXT : farm);
        goatOwner.setPhone((phone.isEmpty()) ? DEFAULT_TEXT : phone);
        
        if (!tag.isEmpty()) {
            goatOwner.setGoatTag(tag);

            AppUtils.addGoatOwner(goatOwner, this);
            GoatOwnerScreen.ownerTable.setModel(new DefaultTableModel(null, new Object[]{"ID", "Name", "Address", "Phone", "Farm", "Goat Tag"}));
            AppUtils.fillGoatOwnerTable(GoatOwnerScreen.ownerTable, "");
        }
        
    }//GEN-LAST:event_addVaccinationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccinationBtn;
    private javax.swing.JButton cancelDeworm;
    private javax.swing.JComboBox<String> goatTags;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ownerAddress;
    private javax.swing.JTextField ownerFarm;
    private javax.swing.JTextField ownerName;
    private javax.swing.JTextField ownerPhone;
    // End of variables declaration//GEN-END:variables
}
