/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.models.Goat;
import app.models.GoatOwner;
import app.utils.AppUtils;
import connector.DbConnection;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.Global.undefined;

/**
 *
 * @author Eco
 */
public class PrintReport extends javax.swing.JFrame {

    /**
     * Creates new form PrintReporrt
     */
    private Goat goat;
    private static Connection conn;
    
    public PrintReport() {
        initComponents();
        conn = DbConnection.getConnection();
    }

    
    public void selectedGoat(Goat selectedGoat) {
        goat = selectedGoat;
        
        if (goat != null) {
            populateDetails();
        }
    }
    
    private void populateDetails() {
        goatTag.setText(goat.getID());
        goatBreed.setText(goat.getBreed());
        goatDOB.setText(goat.getBirthDate());
        goatSireTag.setText(goat.getBuck_id());
        goatDoeTag.setText(goat.getDoe_id());
        
        ImageIcon imageSide = new ImageIcon(new ImageIcon(goat.getImage_side())
                .getImage()
                .getScaledInstance(goatImage.getWidth(), goatImage.getHeight(), Image.SCALE_SMOOTH)
        );
        goatImage.setIcon(imageSide);
        getOwnerInfo();
    }
    
    public void getOwnerInfo() {
        GoatOwner owner = new GoatOwner();
        
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement("SELECT * FROM `goatowner` WHERE `goatID` = ? ");
            ps.setString(1, goat.getID());
            
            ResultSet rs = ps.executeQuery();
          
            while(rs.next()) {
                owner.setId(rs.getInt(1));
                owner.setName(rs.getString(2));
                owner.setAdress(rs.getString(3));
                owner.setPhone(rs.getString(4));
                owner.setFarm(rs.getString(5));
                owner.setGoatTag(goat.getID());
            }
        } catch (SQLException ex) {
            Logger.getLogger(AppUtils.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        if (owner != null || owner != undefined) {
            goatOwnerName.setText(owner.getName());
            goatOwnerAddress.setText(owner.getAdress());
            goatOwnerPhone.setText(owner.getPhone());
            goatOwnerFarm.setText(owner.getFarm());
        } else {
            System.out.println("Null");
            goatOwnerName.setText("No record");
            goatOwnerAddress.setText("No record");
            goatOwnerPhone.setText("No record");
            goatOwnerFarm.setText("No record");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        goatImage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        goatSireTag = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        goatBreed = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goatDOB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        goatTag = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        goatDoeTag = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        goatOwnerAddress = new javax.swing.JLabel();
        goatOwnerFarm = new javax.swing.JLabel();
        goatOwnerName = new javax.swing.JLabel();
        goatOwnerPhone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("KATEBE FARM LIMITED ANIMAL PROFILE RECORD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 820, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(goatImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 250));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goatSireTag.setText("HDJ78");
        jPanel4.add(goatSireTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 20));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("TAG NO:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        goatBreed.setText("Local");
        jPanel4.add(goatBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 20));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Date of Birth:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        goatDOB.setText("09-04-1992");
        jPanel4.add(goatDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, 20));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("LIINEAGE");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 159, -1, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 450, 10));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Breed:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        goatTag.setText("UGONS");
        jPanel4.add(goatTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, 20));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Doe Tag NO:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        goatDoeTag.setText("SHDK90");
        jPanel4.add(goatDoeTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("Sire Tag NO:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 490, 330));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 10));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("OWNER INFORMATION");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 9, -1, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Farm:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setText("Name:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setText("Address:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("Phone:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        goatOwnerAddress.setText("Kitintiale");
        jPanel5.add(goatOwnerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, 20));

        goatOwnerFarm.setText("DT Farm");
        jPanel5.add(goatOwnerFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 20));

        goatOwnerName.setText("Denis");
        jPanel5.add(goatOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 20));

        goatOwnerPhone.setText("90768790");
        jPanel5.add(goatOwnerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 420, 350));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goatBreed;
    private javax.swing.JLabel goatDOB;
    private javax.swing.JLabel goatDoeTag;
    private javax.swing.JLabel goatImage;
    private javax.swing.JLabel goatOwnerAddress;
    private javax.swing.JLabel goatOwnerFarm;
    private javax.swing.JLabel goatOwnerName;
    private javax.swing.JLabel goatOwnerPhone;
    private javax.swing.JLabel goatSireTag;
    private javax.swing.JLabel goatTag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
